### ISSUE TITLE
Reading include_locations from compile_commands.json?

### ISSUE THREAD

**Issue by bblanchon** [pieterverstraete/include_autocomplete#2]
Hi!

Thank you very much for this awesome plugin.
The completion of includes is the thing I miss the most in SublimeText.
However, maintaining the `include_locations` quickly becomes a burden in a large project.

I think a way to address that is to read the [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html).
This file is usually generated by CMake and is used by many other tools like clang-tidy, SourceTrail...
It contains the compiler command line from which you can infer the include locations.

You may have a look at the [EasyClangComplete](https://packagecontrol.io/packages/EasyClangComplete) plugin, which does exactly that.

Regards,
Benoit

**Comment by rwols** [comment]
I agree this would be a nice addition. @pieterverstraete is it okay if I implement this or do you want to do it?

**Comment by pieterverstraete** [comment]
That indeed looks very interesting, but I'm not very familiar with it. So if you feel like implementing it, you are most welcome to contribute! ;)

**Comment by pieterverstraete** [comment]
Fixed by @rwols and merged in #3
Thanks!
