### ISSUE TITLE
[Bug] Plugin is searching in invalid include paths

### ISSUE THREAD

**Issue by papadokolos** [pieterverstraete/include_autocomplete#7]
### Brief Description
The plugin ignores the "directory" entry of the  _compile-commands.json_ file. See #6  for more information.

### My System Specification
- **Operating System:**
    Ubuntu 14.04 32bit (VirtualBox)
- **Sublime Text Version:**
    Sublime Text 3 Build 3126

**Comment by pieterverstraete** [comment]
Thanks for the feedback. This should be fixed by #6.
